#ifndef CACHE_MODE_H
#define CACHE_MODE_H
#define MIRAGE 1
#define ENIGMA_ENABLE_SSL_SRRIP 1
#define ENIGMA_ENABLE_SOS_SUPERVISOR 1
#define ENIGMA_USE_GLOBAL_RANDOM_DATA 0
#define LLC_SECURITY_MODE "enigma+maya"
#define ENIGMA_SOS_THRESHOLD 2
#endif
